version: '3.8'

services:

  server:
    container_name: node_server
    build: ./server
    ports:
      - '3000:3000'
    environment:
      - EXTERNAL_PORT=5432
      - PGUSER=admin
      - PGPASSWORD=admin
      - PGDATABASE=postgres
      - PGHOST=db
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
    - '5432:5432'