version: '3'

services:

  api:
    container_name: api
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
    - '5432:5432'